import { lazy } from "react";

const MemoryMatch = lazy(() => import("../MemoryMatch/MemoryMatch.jsx"));
const StackTower = lazy(() => import("../StackTower/StackTower.jsx"));
const Snake = lazy(() => import("../Snake/Snake.jsx"));
const TileMatch = lazy(() => import("../TileMatch/TileMatch.jsx"));
const BubblePop = lazy(() => import("../BubblePop/BubblePop.jsx"));
const Jigsaw = lazy(() => import("../Jigsaw/Jigsaw.jsx"));
const CatchTheItem = lazy(() => import("../CatchTheItem/CatchTheItem.jsx"));
const FruitMerge = lazy(() => import("../FruitMerge/FruitMerge.jsx"));
const WhackAMole = lazy(() => import("../WhackAMole/WhackAMole.jsx"));
const TargetTap = lazy(() => import("../TargetTap/TargetTap.jsx"));
const ColorMatch = lazy(() => import("../ColorMatch/ColorMatch.jsx"));
const FindTheItem = lazy(() => import("../FindTheItem/FindTheItem.jsx"));
const FluffyFlap = lazy(() => import("../FluffyFlap/FluffyFlap.jsx"));
const FollowMe = lazy(() => import("../FollowMe/FollowMe.jsx"));
const GuessTheBox = lazy(() => import("../GuessTheBox/GuessTheBox.jsx"));
const Reflex = lazy(() => import("../Reflex/Reflex.jsx"));
const TugOfWar = lazy(() => import("../TugOfWar/TugOfWar.jsx"));
const FluffyBlocks = lazy(() => import("../FluffyBlocks/FluffyBlocks.jsx"));
const LaundryToss = lazy(() => import("../LaundryToss/LaundryToss.jsx"));
const LaundryRush = lazy(() => import("../LaundryRush/LaundryRush.jsx"));
const TidyTogether = lazy(() => import("../TidyTogether/TidyTogether.jsx"));
const FruitSudoku = lazy(() => import("../FruitSudoku/FruitSudoku.jsx"));
const CloudHop = lazy(() => import("../CloudHop/CloudHop.jsx"));
const ConnectPairs = lazy(() => import("../ConnectPairs/ConnectPairs.jsx"));
const FluffyHockey = lazy(() => import("../FluffyHockey/FluffyHockey.jsx"));
const SnackSnap = lazy(() => import("../SnackSnap/SnackSnap.jsx"));
const FluffySumo = lazy(() => import("../FluffySumo/FluffySumo.jsx"));
const SnowballFight = lazy(() => import("../SnowballFight/SnowballFight.jsx"));
const FluffyVolley = lazy(() => import("../FluffyVolley/FluffyVolley.jsx"));

// Single source of truth for every Fluffy Play game. Adding a new game means
// adding one entry here (plus its component file) — GameHub, GamePage,
// filters and routing all read from this array. The "Together" tag marks
// games with a same-device 2-player mode (parent & child).
export const games = [
  {
    id: "memory",
    title: "Memory Match",
    tagline: "Find the matching products",
    description: "Flip the cards and find every matching Fluffy pair — solo, or take turns with a partner.",
    tags: ["Puzzle", "Family", "Together"],
    difficulty: "easy",
    duration: "2-4 min",
    engine: "react",
    accent: "#0477b6",
    icon: "Shirt",
    featured: true,
    component: MemoryMatch,
  },
  {
    id: "stack",
    title: "Stack Tower",
    tagline: "How high can you stack?",
    description: "Time your tap to drop each block and build the tallest, straightest Fluffy tower.",
    tags: ["Quick", "Classic"],
    difficulty: "medium",
    duration: "1-2 min",
    engine: "canvas",
    accent: "#d9a85b",
    icon: "Layers",
    component: StackTower,
  },
  {
    id: "snake",
    title: "Snake",
    tagline: "Classic snake game",
    description: "Guide the Fluffy snake to collect treats without running into yourself.",
    tags: ["Classic", "Family"],
    difficulty: "medium",
    duration: "1-3 min",
    engine: "canvas",
    accent: "#60bb8f",
    icon: "Zap",
    component: Snake,
  },
  {
    id: "tile-match",
    title: "Tile Match",
    tagline: "Match the Fluffy tiles",
    description: "Clear tiles in matching pairs before the clock runs out and level up the fun.",
    tags: ["Puzzle", "Quick"],
    difficulty: "easy",
    duration: "1 min",
    engine: "react",
    accent: "#e08ba0",
    icon: "LayoutGrid",
    component: TileMatch,
  },
  {
    id: "bubble-pop",
    title: "Bubble Pop",
    tagline: "Swipe to pop them all",
    description: "Swipe through floating bubbles to pop whole chains at once — burst bubbles clear everything nearby. Play solo, or race a partner on one screen.",
    tags: ["Quick", "Family", "Together"],
    difficulty: "easy",
    duration: "40-45 sec",
    engine: "dom",
    accent: "#68add3",
    icon: "Sparkles",
    component: BubblePop,
  },
  {
    id: "jigsaw",
    title: "Jigsaw Puzzle",
    tagline: "Piece your favorite look together",
    description: "Classic interlocking pieces — piece together a Fluffy look, or upload your own photo.",
    tags: ["Puzzle", "Family"],
    difficulty: "medium",
    duration: "2-5 min",
    engine: "react",
    accent: "#0477b6",
    icon: "Puzzle",
    component: Jigsaw,
  },
  {
    id: "catch",
    title: "Catch the Item",
    tagline: "Catch what falls",
    description: "Move the basket to catch falling Fluffy items — they fall faster the longer you survive.",
    tags: ["Quick", "Family"],
    difficulty: "easy",
    duration: "Endless",
    engine: "kaboom",
    accent: "#0477b6",
    icon: "Heart",
    component: CatchTheItem,
  },
  {
    id: "fruit-merge",
    title: "Fruit Merge",
    tagline: "Merge to grow bigger",
    description: "Drop and merge matching pieces into bigger ones without letting the stack overflow.",
    tags: ["Puzzle", "Quick"],
    difficulty: "medium",
    duration: "2-4 min",
    engine: "kaboom",
    accent: "#60bb8f",
    icon: "Sparkles",
    component: FruitMerge,
  },
  {
    id: "whack-a-mole",
    title: "Whack-a-Mole",
    tagline: "Quick reflexes wanted",
    description: "Tap the moles the instant they pop up and chain combos — but never whack the polar bear!",
    tags: ["Quick", "Family", "Classic"],
    difficulty: "easy",
    duration: "30 sec",
    engine: "react",
    accent: "#d9a85b",
    icon: "Target",
    component: WhackAMole,
  },
  {
    id: "target-tap",
    title: "Target Tap",
    tagline: "Precision under pressure",
    description: "Hit each shrinking target dead center to build a Perfect streak up to ×3 — let one vanish and you lose a heart.",
    tags: ["Quick", "Family"],
    difficulty: "medium",
    duration: "30 sec",
    engine: "react",
    accent: "#e08ba0",
    icon: "Target",
    component: TargetTap,
  },
  {
    id: "color-match",
    title: "Color Match",
    tagline: "Find the matching color",
    description: "Spot the item that matches each color — every color has its own shape and name, too.",
    tags: ["Puzzle", "Family"],
    difficulty: "easy",
    duration: "45 sec",
    engine: "react",
    accent: "#8e4ec6",
    icon: "Sparkles",
    component: ColorMatch,
  },
  {
    id: "find-item",
    title: "Find the Item",
    tagline: "Spot the hidden things",
    description: "Search a cozy, cluttered room for the items on your list — or spot the odd one out in a growing grid.",
    tags: ["Puzzle", "Family"],
    difficulty: "easy",
    duration: "1 min",
    engine: "react",
    accent: "#d9a85b",
    icon: "Star",
    component: FindTheItem,
  },
  {
    id: "fluffy-flap",
    title: "Fluffy Flap",
    tagline: "Tap to fly",
    description: "Tap to keep Fluffy floating through the soft gates — grab treats along the way for bonus points.",
    tags: ["Quick", "Classic"],
    difficulty: "medium",
    duration: "Endless",
    engine: "kaboom",
    accent: "#68add3",
    icon: "Heart",
    component: FluffyFlap,
  },
  {
    id: "follow-me",
    title: "Follow Me",
    tagline: "Repeat the pattern",
    description: "Watch the pads light up, then play the pattern back — it grows by one each round. Play solo or take turns with a partner.",
    tags: ["Puzzle", "Family", "Together"],
    difficulty: "easy",
    duration: "1-3 min",
    engine: "react",
    accent: "#8e4ec6",
    icon: "Star",
    component: FollowMe,
  },
  {
    id: "guess-box",
    title: "Guess the Box",
    tagline: "Keep your eye on the teddy",
    description: "The teddy hides under a gift box, the boxes shuffle — can you tell where it went? Or take turns hiding it for each other.",
    tags: ["Quick", "Family", "Together"],
    difficulty: "easy",
    duration: "1-3 min",
    engine: "react",
    accent: "#d9a85b",
    icon: "Gift",
    component: GuessTheBox,
  },
  {
    id: "reflex",
    title: "Fluffy Reflex",
    tagline: "How fast are you?",
    description: "Wait for the treat to pop up, then tap as fast as you can. Five tries — your average reaction time is your score.",
    tags: ["Quick", "Family"],
    difficulty: "easy",
    duration: "30 sec",
    engine: "react",
    accent: "#e08ba0",
    icon: "Zap",
    component: Reflex,
  },
  {
    id: "tug",
    title: "Fluffy Tug",
    tagline: "Tap to pull the ribbon",
    description: "A tug of war for two on one screen — tap your half as fast as you can to pull the ribbon home. Kids' taps count double.",
    tags: ["Quick", "Family", "Together"],
    difficulty: "easy",
    duration: "30 sec",
    engine: "react",
    accent: "#0477b6",
    icon: "Heart",
    component: TugOfWar,
  },
  {
    id: "blocks",
    title: "Fluffy Blocks",
    tagline: "Fit the fabric pieces",
    description: "Drag fabric pieces onto the board and fill rows or columns to clear them. Easy to learn, hard to master, with a daily run that's the same for everyone.",
    tags: ["Puzzle", "Classic"],
    difficulty: "medium",
    duration: "3-6 min",
    engine: "react",
    accent: "#8e4ec6",
    icon: "LayoutGrid",
    component: FluffyBlocks,
  },
  {
    id: "laundry-toss",
    title: "Laundry Toss",
    tagline: "Flick clothes into the basket",
    description: "Flick the clothes up into a drifting laundry basket. Aim ahead of it, and watch out for the wind!",
    tags: ["Quick", "Family"],
    difficulty: "medium",
    duration: "1 min",
    engine: "kaboom",
    accent: "#68add3",
    icon: "Shirt",
    component: LaundryToss,
  },
  {
    id: "laundry-rush",
    title: "Laundry Rush",
    tagline: "Sort fast, keep the combo",
    description: "Swipe each item into the right bin before its ring runs out. Every 10 items the rule flips between type and color. One mistake breaks the combo!",
    tags: ["Quick", "Puzzle"],
    difficulty: "medium",
    duration: "1 min",
    engine: "react",
    accent: "#e08ba0",
    icon: "Zap",
    component: LaundryRush,
  },
  {
    id: "tidy-together",
    title: "Tidy Together",
    tagline: "Clean up as a team",
    description: "Things tumble down: drag each one into the right basket. Two people can drag at the same time on one screen. Nobody loses, just tidy up together.",
    tags: ["Family", "Together"],
    difficulty: "easy",
    duration: "1-2 min",
    engine: "react",
    accent: "#60bb8f",
    icon: "Heart",
    component: TidyTogether,
  },
  {
    id: "fruit-sudoku",
    title: "Fruit Sudoku",
    tagline: "One of each fruit",
    description: "Sudoku with fruit instead of numbers: 4x4 for little ones, 6x6 for grown-ups, plus a daily puzzle that's the same for everyone. No timer pressure.",
    tags: ["Puzzle", "Family"],
    difficulty: "easy",
    duration: "2-6 min",
    engine: "react",
    accent: "#60bb8f",
    icon: "Cherry",
    component: FruitSudoku,
  },
  {
    id: "cloud-hop",
    title: "Cloud Hop",
    tagline: "Bounce up the clouds",
    description: "Fluffy bounces on its own. Slide left and right to land on the next cloud and climb as high as you can, with a daily climb that's the same for everyone.",
    tags: ["Quick", "Classic"],
    difficulty: "medium",
    duration: "Endless",
    engine: "kaboom",
    accent: "#68add3",
    icon: "Star",
    component: CloudHop,
  },
  {
    id: "connect-pairs",
    title: "Connect Pairs",
    tagline: "Join every matching pair",
    description: "Draw paths between matching dots without crossing, and fill every square. Five puzzles from 5x5 to 7x7, plus a daily pack that's the same for everyone.",
    tags: ["Puzzle", "Family"],
    difficulty: "medium",
    duration: "3-8 min",
    engine: "react",
    accent: "#8e4ec6",
    icon: "Puzzle",
    component: ConnectPairs,
  },
  {
    id: "air-hockey",
    title: "Fluffy Hockey",
    tagline: "Air hockey for two",
    description: "Two players, one screen: drag your paddle and knock the cookie into the other goal. First to 5 wins. Kids get a bigger paddle and a smaller goal.",
    tags: ["Family", "Together"],
    difficulty: "easy",
    duration: "2-4 min",
    engine: "canvas",
    accent: "#0477b6",
    icon: "Target",
    component: FluffyHockey,
  },
  {
    id: "snack-snap",
    title: "Snack Snap",
    tagline: "Chomp more snacks than your partner",
    description: "Fruit rolls around the table: tap your half and your chomper lunges to snap it up. Two players, one screen, 45 seconds. Kids get a bigger mouth.",
    tags: ["Quick", "Family", "Together"],
    difficulty: "easy",
    duration: "45 sec",
    engine: "canvas",
    accent: "#60bb8f",
    icon: "Cherry",
    component: SnackSnap,
  },
  {
    id: "fluffy-sumo",
    title: "Fluffy Sumo",
    tagline: "Bump them off the ice",
    description: "Two players, one screen: drag like a joystick to push your Fluffy and bump the other out of the icy ring. First to 3 rounds. A Kid's Fluffy is heavier.",
    tags: ["Family", "Together"],
    difficulty: "easy",
    duration: "1-3 min",
    engine: "canvas",
    accent: "#68add3",
    icon: "Heart",
    component: FluffySumo,
  },
  {
    id: "snowball-fight",
    title: "Snowball Fight",
    tagline: "Throw, dodge, hide behind forts",
    description: "Two players, one screen: slide to move, flick or tap to throw snowballs, and hide behind snow forts that crumble, slide and shuffle, and grab power-ups: shield, rapid fire, triple shot. First to 5 hits wins.",
    tags: ["Quick", "Family", "Together"],
    difficulty: "easy",
    duration: "1-3 min",
    engine: "canvas",
    accent: "#68add3",
    icon: "Sparkles",
    component: SnowballFight,
  },
  {
    id: "fluffy-volley",
    title: "Fluffy Volley",
    tagline: "Head it over the net",
    description: "Two players side by side: touch your half to run and hop, and head the ball over the net. If it lands on your side, the other player scores. First to 5.",
    tags: ["Family", "Together"],
    difficulty: "medium",
    duration: "2-4 min",
    engine: "kaboom",
    accent: "#e08ba0",
    icon: "Star",
    component: FluffyVolley,
  },
];

// Games merged into another one keep their old links working.
const MERGED_IDS = { "bubble-race": "bubble-pop" };

export function getGameById(id) {
  const target = MERGED_IDS[id] ?? id;
  return games.find((game) => game.id === target) ?? null;
}
